name: h2integrate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - glpk
  # - coin-or-cbc=2.10.8  # NOTE: uncomment if on Unix
  # - wisdem  # NOTE: uncomment if installing with Ard
  - pip
  - pip:
    - "."
