name: "plant_config"
description: "This plant is located in Denmark"

sites:
  site:
    latitude: 56.22732285
    longitude: 8.594398
    resources:
      # wind resource is handled directly in the Ard wrapper
      solar_resource:
        resource_model: "goes_aggregated_solar_v4_api"
        resource_parameters:
          resource_year: 2013
          resource_dir: "../11_hybrid_energy_plant/tech_inputs/weather/solar"
          resource_filename: "30.6617_-101.7096_psmv3_60_2013.csv"


plant:
  plant_life: 30

technology_interconnections: [
  ["wind", "combiner", "electricity", "cable"], #source_tech, dest_tech, transport_item, transport_type = connection
  ["solar", "combiner", "electricity", "cable"],
  ["combiner", "battery", "electricity", "cable"],
  # etc
]

resource_to_tech_connections: [
  # connect the wind resource to the wind technology
  ['site.solar_resource', 'solar', 'solar_resource_data'],
]

finance_parameters:
  finance_groups:
    finance_model: "ProFastComp"
    model_inputs:
      params:
        analysis_start_year: 2025
        installation_time: 36 # months
        inflation_rate: 0.0 # 0 for real analysis
        discount_rate: 0.09 # nominal return based on 2024 ATB baseline workbook for land-based wind
        debt_equity_ratio: 2.62 # 2024 ATB uses 72.4% debt for land-based wind
        property_tax_and_insurance: 0.03 # percent of CAPEX estimated based on https://www.nrel.gov/docs/fy25osti/91775.pdf  https://www.house.mn.gov/hrd/issinfo/clsrates.aspx
        total_income_tax_rate: 0.257 # 0.257 tax rate in 2024 atb baseline workbook, value here is based on federal (21%) and state in MN (9.8)
        capital_gains_tax_rate: 0.15 # H2FAST default
        sales_tax_rate: 0.07375 # total state and local sales tax in St. Louis County https://taxmaps.state.mn.us/salestax/
        debt_interest_rate: 0.07 # based on 2024 ATB nominal interest rate for land-based wind
        debt_type: "Revolving debt" # can be "Revolving debt" or "One time loan". Revolving debt is H2FAST default and leads to much lower LCOH
        loan_period_if_used: 0 # H2FAST default, not used for revolving debt
        cash_onhand_months: 1 # H2FAST default
        admin_expense: 0.00 # percent of sales H2FAST default
      capital_items:
        depr_type: "MACRS" # can be "MACRS" or "Straight line"
        depr_period: 5 # 5  years - for clean energy facilities as specified by the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
        refurb: [0.]
  cost_adjustment_parameters:
    cost_year_adjustment_inflation: 0.025 # used to adjust modeled costs to target_dollar_year
    target_dollar_year: 2025
  finance_subgroups:
    dispatched_electricity:
      commodity: "electricity"
      commodity_stream: "battery"
      technologies: ["wind", "solar", "battery"]
    produced_electricity:
      commodity: "electricity"
      commodity_stream: "combiner"
      technologies: ["wind", "solar"]
