name: "technology_config"
description: "This plant is located in Denmark. The plant combines wind and solar generation with a battery to meet a constant load"

technologies:
  wind:
    performance_model:
      model: "ard_wind_plant_combined"
    cost_model:
      model: "ard_wind_plant_combined"
    model_inputs:
      performance_parameters:
        ard_data_path: "./"
        ard_system:
          system: "onshore_batch"
          modeling_options:
            windIO_plant: !include ../ard_inputs/windio.yaml
            layout:
              N_turbines: 9
              N_substations: 1
              spacing_primary: 7.0
              spacing_secondary: 7.0
              angle_orientation: 0.0
              angle_skew: 0.0
            aero:
              return_turbine_output: False
            floris:
              peak_shaving_fraction: 0.2
              peak_shaving_TI_threshold: 0.0
            collection:
              max_turbines_per_string: 8
              solver_name: "highs"
              solver_options:
                time_limit: 60
                mip_gap: 0.02
              model_options:
                topology: "branched"  # "radial", "branched"
                feeder_route: "segmented"
                feeder_limit: "unlimited"
            offshore: false
            floating: false
            costs:
              rated_power: 5000000.0  # W
              num_blades: 3
              rated_thrust_N: 823484.4216152605 # from NREL 5MW definition
              gust_velocity_m_per_s: 70.0 # from https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/nrel5mw.yaml
              blade_surface_area: 69.7974979
              tower_mass: 620.4407337521
              nacelle_mass: 101.98582836439
              hub_mass: 8.38407517646
              blade_mass: 14.56341339641
              foundation_height: 0.0
              commissioning_cost_kW: 44.0 # from https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/nrel5mw.yaml
              decommissioning_cost_kW: 58.0 # from https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/nrel5mw.yaml
              trench_len_to_substation_km: 50.0
              distance_to_interconnect_mi: 4.97096954
              interconnect_voltage_kV: 130.0 # from https://github.com/WISDEM/WISDEM/blob/master/examples/02_reference_turbines/nrel5mw.yaml
              tcc_per_kW: 1300.00  # (USD/kW)
              opex_per_kW: 44.00  # (USD/kWh)
          analysis_options:
      cost_parameters:
        cost_year: 2024
  solar:
    performance_model:
      model: "pysam_solar_plant_performance"
    cost_model:
      model: "atb_utility_pv_cost"
    model_inputs:
      performance_parameters:
        pv_capacity_kWdc: 50000 # 50 MW
        dc_ac_ratio: 1.34
        create_model_from: "new"
        tilt_angle_func: "none"
        tilt: 0
        pysam_options:
          SystemDesign:
            gcr: 0.3
            array_type: 0 # fixed, non-tracking
            bifaciality: 0.65
            inv_eff: 96.0
            losses: 14.6
            module_type: 1
            azimuth: 180
            rotlim: 45
          SolarResource:
            albedo_default: 0.2
      cost_parameters:
        capex_per_kWac: 1193
        opex_per_kWac_per_year: 18
        cost_year: 2024
  combiner:
    performance_model:
      model: "combiner_performance"
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_units: kW
  battery:
    performance_model:
      model: "simple_generic_storage"
    cost_model:
      model: "atb_battery_cost"
    control_strategy:
      model: "demand_open_loop_storage_controller"
    model_inputs:
      shared_parameters:
        commodity_name: "electricity"
        commodity_units: "kW"
        max_charge_rate: 95000.0  # kW/time step
        max_capacity: 190000.0  # kWh
      control_parameters:
        max_charge_percent: 1.0  # percent as decimal
        min_charge_percent: 0.1  # percent as decimal
        init_charge_percent: 0.25  # percent as decimal
        max_discharge_rate: 95000.0  # kW/time step
        charge_efficiency: 0.985 # percent as decimal
        discharge_efficiency: 0.985 # percent as decimal
        demand_profile: 30000
      cost_parameters:
        cost_year: 2022
        energy_capex: 72.54 # $/kWh
        power_capex: 18.72 # $/kW
        opex_fraction: 0.02 # percent of capex
