name: "plant_config"
description: "Configures an iron electrowinning system."

site:
  latitude: 41.717
  longitude: -88.398

technology_interconnections: [
  # Connect feedstocks to iron mine.
  # Requires `electricity` and `crude ore`.
  # Both are set up as generic feedstock components - see tech_config.
  ["grid_feedstock","iron_mine","electricity","cable"],
  ["mine_feedstock","iron_mine","crude_ore","pipe"],
  # Connect feedstocks to iron electrowinning plant.
  # Requires `electricity` and `iron_ore`.
  # Electricity is set up as generic feedstock component,
  # but iron_ore is set up as an output of an iron_mine.
  ["iron_mine","iron_plant","iron_ore","iron_transport"],
  ["ewin_grid_feedstock","iron_plant","electricity","cable"],
]

plant:
  plant_life: 30
finance_parameters:
  finance_groups:
    finance_model: "ProFastComp"
    model_inputs:
      params:
        analysis_start_year: 2032
        installation_time: 36 # months
        inflation_rate: 0.0 # 0 for nominal analysis
        discount_rate: 0.09 # nominal return based on 2024 ATB baseline workbook for land-based wind
        debt_equity_ratio: 2.62 # 2024 ATB uses 72.4% debt for land-based wind
        property_tax_and_insurance: 0.03 # percent of CAPEX estimated based on https://www.nrel.gov/docs/fy25osti/91775.pdf  https://www.house.mn.gov/hrd/issinfo/clsrates.aspx
        total_income_tax_rate: 0.257 # 0.257 tax rate in 2024 atb baseline workbook, value here is based on federal (21%) and state in MN (9.8)
        capital_gains_tax_rate: 0.15 # H2FAST default
        sales_tax_rate: 0.07375 # total state and local sales tax in St. Louis County https://taxmaps.state.mn.us/salestax/
        debt_interest_rate: 0.07 # based on 2024 ATB nominal interest rate for land-based wind
        debt_type: "Revolving debt" # can be "Revolving debt" or "One time loan". Revolving debt is H2FAST default and leads to much lower LCOH
        loan_period_if_used: 0 # H2FAST default, not used for revolving debt
        cash_onhand_months: 1 # H2FAST default
        admin_expense: 0.00 # percent of sales H2FAST default
      capital_items:
        depr_type: "MACRS" # can be "MACRS" or "Straight line"
        depr_period: 5 # 5  years - for clean energy facilities as specified by the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
        refurb: [0.]
  cost_adjustment_parameters:
    cost_year_adjustment_inflation: 0.025
    target_dollar_year: 2022
  finance_subgroups:
    iron_ore:
      commodity: "iron_ore"
      commodity_stream: "iron_mine"
      technologies: ["iron_mine", "grid_feedstock", "mine_feedstock"]
    sponge_iron:
      commodity: "sponge_iron"
      commodity_stream: "iron_plant"
      technologies:
      - "iron_mine"
      - "grid_feedstock"
      - "mine_feedstock"
      - "iron_transport"
      - "iron_plant"
      - "ewin_grid_feedstock"
